/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package lorena

import discord4j.core.DiscordClient
import discord4j.core.event.domain.message.MessageCreateEvent
import discord4j.core.event.domain.message.ReactionAddEvent
import discord4j.core.event.domain.message.ReactionRemoveEvent
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.reactive.asFlow
import kotlinx.coroutines.reactive.awaitSingle
import kotlinx.coroutines.reactor.mono
import org.apache.logging.log4j.LogManager
import org.apache.logging.log4j.Logger
import reactor.util.Loggers
import io.github.cdimascio.dotenv.dotenv

class Bot {
    val logger: Logger = LogManager.getLogger()
    val dotenv = dotenv()
    val testingFlag = true
}

fun main(args: Array<String>) {
    val client = DiscordClient.create(Bot().dotenv["TOKEN"])
    

    Loggers.useConsoleLoggers()

    client.withGateway {
        mono {
            //Bot commands list
            it.on(MessageCreateEvent::class.java)
                    .asFlow()
                    .collect {
                        val message = it.message
                        val parsedMessage = message.content.split(" ")
                        if(parsedMessage[0] == "!lore") {
                            when(parsedMessage[1]) {
                                "ping" -> {
                                    val channel = message.channel.awaitSingle()
                                    channel.createMessage("Pong!").awaitSingle()
                                }

                                "marco" -> {
                                    val channel = message.channel.awaitSingle()
                                    channel.createMessage("Polo!").awaitSingle()
                                }

                                "usercount" -> {
                                    val channel = message.channel.awaitSingle()
                                    channel.createMessage("usercount not implemented yet").awaitSingle()
                                }

                                "list" -> {
                                    when(parsedMessage[2]) {
                                        "me" -> {
                                            val channel = message.channel.awaitSingle()
                                            channel.createMessage("list me not implemented yet").awaitSingle()
                                        }

                                        "all" -> {
                                            val channel = message.channel.awaitSingle()
                                            channel.createMessage("list all not implemented yet").awaitSingle()
                                        }
                                    }
                                }
                            }
                        }
                    }
            /* Reaction event handling*/
            // Added Reaction
            it.on(ReactionAddEvent::class.java)
                    .asFlow()
                    .collect {
                        TODO()
                    }
            // Removed Reaction
            it.on(ReactionRemoveEvent::class.java)
                    .asFlow()
                    .collect {
                        TODO()
                    }
        }
    }
            .block()
}
